# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias lv='ls -l --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

HOME_DIR=/home/zhaopan
# some more ls aliases
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'
#更改gdb的启动配置信息
alias gdb='gdb -x ~/.gdbcfg'
alias vi='vim'
alias cdnotes='cd $HOME_DIR/myNotes/bash_scripts'
alias cd1='cd ../'
alias cd2='cd ../../'
alias cd3='cd ../../../'
alias cdqt540='cd $HOME_DIR/work/qt540'
alias cdwebengine='cd $HOME_DIR/work/qt540/qtwebengine/src/3rdparty/chromium/third_party/WebKit'
alias cdcmoswebkit='cd $HOME_DIR/work/qtwebkit5/'
alias cdbuilccmoswebkit='cd $HOME_DIR/work/b-cmos-webkit'
alias cdwww='cd /var/www'
alias cdwork='cd $HOME_DIR/work'
alias cd20='cd $HOME_DIR/work/2.0'
alias cdphotoPlugin='cd $HOME_DIR/work/2.0/qmlplugin-multimedia-photos'
alias cdbrowser='cd $HOME_DIR/work/browser/'
alias cdb-browser='cd $HOME_DIR/work/b-browser'
alias cdsdkb-browser='cd $HOME_DIR/work/sdk-build/b-browser'
alias cdsdkcompile='cd $HOME_DIR/work/sdk-build'
alias cdsdkdownload='cd $HOME_DIR/work/sdk-build/cmos-download'
alias cdsdkb-download='cd $HOME_DIR/work/sdk-build/b-cmos-download'
alias cdsdk='cd $HOME_DIR/work/sdk-build/'
alias cdqt='cd $HOME_DIR/work/qt521'
alias cdqt531='cd $HOME_DIR/work/qt531'
alias cd302s='cd $HOME_DIR/work/302s'
alias cdsh='cd $HOME_DIR/work/sh'
alias vt='vi -t'
alias cdexam='cd $HOME_DIR/qt520/qtwebkit-examples/examples/webkitwidgets'
alias gitdiffpre='git diff HEAD^'
alias cddownload='cd $HOME_DIR/work/downloader/'
alias cdxiazai='cd $HOME_DIR/Downloads'
alias cddesktop='cd $HOME_DIR/Desktop'
alias cdchrome_org='cd $HOME_DIR/android/master/external/chromium_org'
alias cddesignbrowser='cd /home/zhaopan/SYBEROS/草稿版/各组材料/浏览器组/设计方案'
alias bundleInstall='vim +BundleInstall +qall'
alias bundleClean='vim +BundleClean +qall'
alias cdbundle='cd /home/zhaopan/.vim/bundle'
alias cdbshell='cdb shell'
alias cdbpush='cdb push'
alias cdbpull='cdb pull'
alias cdstr_replace='cd /home/zhaopan/work/str_replace'
alias install='sudo apt-get install'
alias search='aptitude search'
alias sb2up='sb2 -t syberos-target-armv7tnhl -m sdk-install -R zypper update'
alias sb2ref='sb2 -t syberos-target-armv7tnhl -m sdk-install -R zypper ref'
alias sb2rm='sb2 -t syberos-target-armv7tnhl -m sdk-install -R zypper rm'
alias sb2qmake='sb2 -t syberos-target-armv7tnhl /usr/lib/qt5/bin/qmake'
alias sb2rpmbuild='sb2 -t syberos-target-armv7tnhl rpmbuild -ba'
alias syberossb2='/srv/syberos/sdks/sdk/syberos-sdk-chroot sb2 -t syberos-target-armv7tnhl'
alias cdtest='cd $HOME_DIR/test'
alias cdrpm='cd $HOME_DIR/rpmbuild/RPMS/armv7tnhl'
alias cdextractor='cd $HOME_DIR/work/extractor'
alias cdwatcher='cd /home/zhaopan/work/watcher/watcher/src'
alias vr='vim -R '
alias cdtracker='cd /home/zhaopan/work/tracker-0.17.1.skytree30-1.syberos.10.1.src/tracker-0.17.1.skytree30/tracker'
alias sybersdk='/home/zhaopan/SyberOS-SDK/pdk-jail/sdks/sdk/syberos-sdk-chroot sb2 -t sybersdk-target-armv7tnhl'
alias cdbaihehua='cd ~/work/baihehua'
alias cdsysupdate='cd /home/zhaopan/android/androiddos/android600/packages/apps/SystemUpdate'

M_CHROOT="/home/$USER/Syberos-Pdk/sdk/sdk-root/syberos-sdk-chroot"
alias sb2main="$M_CHROOT sb2 -t target-armv7tnhl-main_dev -m sdk-install -R"
alias sb2lily="$M_CHROOT sb2 -t target-armv7tnhl-product_lily -m sdk-install -R"
alias sb2xuanwu="$M_CHROOT sb2 -t target-armv7tnhl-xuanwu -m sdk-install -R"

# Alias definitions
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

#android
JAVA_HOME=$HOME_DIR/android/sdk-tool/jdk1.7.0_79
export CLASSPATH=$JAVA_HOME/lib:$CLASSPATH
export PATH=$JAVA_HOME/bin:$PATH
export USE_CCACHE=1
export CCACHE_DIR=/home/zhaopan/ccache
#android


export PATH=$HOME_DIR/android/sdk-tool/android-sdk-linux/tools:/home/zhaopan/android/sdk-tool/android-sdk-linux/platform-tools:$PATH
export PATH=$HOME_DIR/myNotes/bash_scripts:$PATH
export PATH=/usr/local/Qt-5.3.1/bin:$PATH
export PATH=$HOME_DIR/chrome-project/depot_tools:$PATH
export PATH=~/bin:$PATH
export PATH=/home/zhaopan/.vim/bundle/YCM-Generator:$PATH
#set -o vi
alias sdk=/srv/syberos/sdks/sdk/syberos-sdk-chroot
alias pdk=/home/zhaopan/Syberos-Pdk/sdk/sdk-root/syberos-sdk-chroot
